//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1DV402.S2.L3C.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_1DV402.S2.L3C.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0. Avsluta.
        /// </summary>
        internal static string aMenuCancel {
            get {
                return ResourceManager.GetString("aMenuCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Cirkel.
        /// </summary>
        internal static string aMenuCirkel {
            get {
                return ResourceManager.GetString("aMenuCirkel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Rätblock.
        /// </summary>
        internal static string aMenuCuboid {
            get {
                return ResourceManager.GetString("aMenuCuboid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Cylinder.
        /// </summary>
        internal static string aMenuCylinder {
            get {
                return ResourceManager.GetString("aMenuCylinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Ellipse.
        /// </summary>
        internal static string aMenuEllipse {
            get {
                return ResourceManager.GetString("aMenuEllipse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----------------------------.
        /// </summary>
        internal static string aMenuHorizontalLine {
            get {
                return ResourceManager.GetString("aMenuHorizontalLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Rektangel.
        /// </summary>
        internal static string aMenuRectangle {
            get {
                return ResourceManager.GetString("aMenuRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6. Sfär.
        /// </summary>
        internal static string aMenuSphere {
            get {
                return ResourceManager.GetString("aMenuSphere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7. Slumpa 2d-figurer.
        /// </summary>
        internal static string aRandomize2D {
            get {
                return ResourceManager.GetString("aRandomize2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8. Slumpa 3d-figurer.
        /// </summary>
        internal static string aRandomize3D {
            get {
                return ResourceManager.GetString("aRandomize3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =============================================.
        /// </summary>
        internal static string bHeadLine37 {
            get {
                return ResourceManager.GetString("bHeadLine37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Figur      Längd Bredd Omkrets  Area.
        /// </summary>
        internal static string bHeadViewShapes2DHeading {
            get {
                return ResourceManager.GetString("bHeadViewShapes2DHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Figur      Längd Bredd  Höjd   Mantelarea  Begränsn.area        Volym.
        /// </summary>
        internal static string bHeadViewShapes3DHeading {
            get {
                return ResourceManager.GetString("bHeadViewShapes3DHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometriska Figurer - Nivå c.
        /// </summary>
        internal static string cHeading {
            get {
                return ResourceManager.GetString("cHeading", resourceCulture);
            }
        }
    }
}
